api:
  host: "0.0.0.0"  # The IP address where the API will listen
  port: 5000        # The port on which the API will listen
  base_url: "/api"  # The base URL of the API
  router: "v1"
  
  timeout:
    request: 30       # Timeout for API requests (in seconds)
    response: 30      # Timeout for API responses (in seconds)

  cors:
    enabled: true
    allowed_origins:
      - "*"  # Allowed domains for CORS

  logging:
    name: "api"
    level: "debug"
    path: "logs"
    file: "api.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  authentication:
    enabled: true
    method: "Bearer Token"  # The method used for API authentication
    token_lifetime: 3600    # Token lifetime (in seconds)

  rate_limiting:
    enabled: true
    max_requests: 1000  # The maximum number of requests allowed to the API
    window: 3600       # Rate limiting window (in seconds)
    response_code: 429 # HTTP response code when rate limit is exceeded
