logging:
  name: "datakapan"
  console:
    reset: true
    level: "debug"
    format: "%(log_color)s%(levelname)s%(reset)s:     %(message)s"
    colors:
      debug: "blue"
      info: "green"
      warning: "yellow"
      error: "red"
      critical: "bold_red"
  file:
    level: "debug"
    path: "logs"
    file: "app.log"
    rotation:
      enabled: true
      max_size: 52428800  # 50MB in bytes
      max_files: 20
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
