pins:
  gpio:
    # GPIO pins for general digital sensors and actuators
    gpio_2: 2   # GPIO2 (SDA1, I2C data line)
    gpio_3: 3   # GPIO3 (SCL1, I2C clock line)
    gpio_4: 4   # GPIO4 (General Purpose)
    gpio_17: 17 # GPIO17 (General Purpose)
    gpio_18: 18 # GPIO18 (PWM, General Purpose)
    gpio_27: 27 # GPIO27 (General Purpose)
    gpio_22: 22 # GPIO22 (General Purpose)
    gpio_23: 23 # GPIO23 (General Purpose)
    gpio_24: 24 # GPIO24 (General Purpose)
    gpio_25: 25 # GPIO25 (General Purpose)
    gpio_5: 5   # GPIO5 (General Purpose)
    gpio_6: 6   # GPIO6 (General Purpose)
    gpio_12: 12 # GPIO12 (PWM0)
    gpio_13: 13 # GPIO13 (PWM1)
    gpio_19: 19 # GPIO19 (SPI MOSI, PWM1)
    gpio_16: 16 # GPIO16 (General Purpose)
    gpio_26: 26 # GPIO26 (General Purpose)
    gpio_20: 20 # GPIO20 (SPI MISO, General Purpose)
    gpio_21: 21 # GPIO21 (SPI SCLK, General Purpose)

  i2c:
    sda: 2      # I2C SDA (GPIO2)
    scl: 3      # I2C SCL (GPIO3)

  spi:
    mosi: 10    # SPI MOSI (GPIO10)
    miso: 9     # SPI MISO (GPIO9)
    sclk: 11    # SPI SCLK (GPIO11)
    cs0: 8      # SPI Chip Select 0 (GPIO8)
    cs1: 7      # SPI Chip Select 1 (GPIO7)

  uart:
    txd: 14     # UART TXD (GPIO14)
    rxd: 15     # UART RXD (GPIO15)

  power:
    vcc_3v3: 1  # 3.3V Power Pin
    vcc_5v: 2   # 5V Power Pin

  ground:
    gnd_6: 6    # Ground Pin
    gnd_9: 9    # Ground Pin
    gnd_14: 14  # Ground Pin
    gnd_20: 20  # Ground Pin
    gnd_25: 25  # Ground Pin
    gnd_30: 30  # Ground Pin
    gnd_34: 34  # Ground Pin
    gnd_39: 39  # Ground Pin
